#!/bin/bash
sudo apt install figlet
figlet installing...
echo -e '\033[0;32m' Update and upgrading....
sudo apt update && sudo apt upgrade
echo -e '\033[0;32m' installing python3...
sudo apt install python3
echo -e '\033[0;32m' installing toilet...
sudo apt install toilet
echo -e '\033[0;32m' installing pip...
sudo apt install pip
echo -e '\033[0;32m' installing colorama...
pip install colorama
echo -e '\033[0;32m' installing pandas
pip install pandas
toilet -t -F gay Done
