#!/bin/bash
echo -e '\033[0;32m' Update and upgrading....
sudo apt update && sudo apt upgrade
echo -e '\033[0;32m' figlet installing...
sudo apt install figlet
echo -e '\033[0;32m' git installing....
sudo apt install git
echo -e '\033[0;32m' installing python3...
sudo apt install python3
echo -e '\033[0;32m' installing toilet...
sudo apt install toilet
echo -e '\033[0;32m' installing pip...
sudo apt install pip
echo -e '\033[0;32m' installing colorama...
pip install colorama
echo -e '\033[0;32m' installing pandas...
pip install pandas
echo -e '\033[0;32m' installing gem...
sudo apt-get install gem
echo -e '\033[0;32m' installing lolcat...
sudo apt-get install lolcat
echo -e '\033[0;32m' installing boxes...
sudo apt-get install boxes
echo -e '\033[0;32m' installing fortunes fortune-mod-cowsay...
sudo apt-get install fortunes fortune-mod cowsay
toilet -t -F gay Done
echo -e '\033[0;32m' Running the program...
python3 Func_List_Mod_Latest.py
