#!/bin/bash
echo -e '\033[0;32m' figlet & toilet installing...
sudo apt install figlet && sudo apt install toilet
toilet -t -F gay installing requirements
figlet updating...
echo -e '\033[0;32m' Update and upgrading....
sudo apt update && sudo apt upgrade
figlet installing python3...
echo -e '\033[0;32m' installing python3...
sudo apt install python3
figlet installing pip...
echo -e '\033[0;32m' installing pip...
sudo apt install pip
figlet installing colorama...
echo -e '\033[0;32m' installing colorama...
pip install colorama
figlet installing pandas...
echo -e '\033[0;32m' installing pandas...
pip install pandas
figlet installing gem...
echo -e '\033[0;32m' installing gem...
sudo apt-get install gem
figlet installing lolcat...
echo -e '\033[0;32m' installing lolcat...
sudo apt-get install lolcat
figlet installing boxes
echo -e '\033[0;32m' installing boxes...
sudo apt-get install boxes
figlet installing fortunes...
echo -e '\033[0;32m' installing fortunes fortune-mod-cowsay...
sudo apt-get install fortunes fortune-mod cowsay
toilet -t -F gay Done
figlet starting...
echo -e '\033[0;32m' Running the program...
python3 Func_List_Mod_Latest.py
